# Generated by Django 3.2 on 2023-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emails_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=200)),
                ('from_address', models.TextField()),
                ('subject', models.TextField()),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='date published')),
            ],
        ),
    ]
